services:
  client:
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=https://thomas-server--3010.prod1.defang.dev
    ports:
      - mode: ingress
        target: 3000
        published: 3000
    deploy:
      resources:
        reservations:
          memory: 2GB
    depends_on:
      - server
  server:
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - target: 4000
        mode: ingress
        published: 4000
